name: Atualizar Grade de TV

on:
  schedule:
    - cron: '0 3 */3 * *'  # Executa automaticamente a cada 3 dias às 03:00 UTC
  workflow_dispatch:       # Ativa o botão para rodar manualmente no GitHub

jobs:
  build:
    runs-runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install pandas requests

      - name: Executar script de processamento
        run: python processar_grade.py

      - name: Salvar Mudanças no Github
        run: |
          git config --global user.name 'GradeBot'
          git config --global user.email 'bot@github.com'
          git add .
          git commit -m "Backup diário e atualização dos catálogos por programa" || exit 0
          git push
